//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace BehaveCore {

public class Crown : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Crown(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Crown obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Crown obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Crown() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          BehaveCorePINVOKE.delete_Crown(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Crown(FuelModels fuelModels) : this(BehaveCorePINVOKE.new_Crown__SWIG_0(FuelModels.getCPtr(fuelModels)), true) {
    if (BehaveCorePINVOKE.SWIGPendingException.Pending) throw BehaveCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public Crown(Crown rhs) : this(BehaveCorePINVOKE.new_Crown__SWIG_1(Crown.getCPtr(rhs)), true) {
    if (BehaveCorePINVOKE.SWIGPendingException.Pending) throw BehaveCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public void doCrownRunRothermel() {
    BehaveCorePINVOKE.Crown_doCrownRunRothermel(swigCPtr);
  }

  public void doCrownRunScottAndReinhardt() {
    BehaveCorePINVOKE.Crown_doCrownRunScottAndReinhardt(swigCPtr);
  }

  public void initializeMembers() {
    BehaveCorePINVOKE.Crown_initializeMembers(swigCPtr);
  }

  public void setFuelModels(FuelModels fuelModels) {
    BehaveCorePINVOKE.Crown_setFuelModels(swigCPtr, FuelModels.getCPtr(fuelModels));
    if (BehaveCorePINVOKE.SWIGPendingException.Pending) throw BehaveCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public void updateCrownInputs(int fuelModelNumber, double moistureOneHour, double moistureTenHour, double moistureHundredHour, double moistureLiveHerbaceous, double moistureLiveWoody, double moistureFoliar, FractionUnits.FractionUnitsEnum moistureUnits, double windSpeed, SpeedUnits.SpeedUnitsEnum windSpeedUnits, WindHeightInputMode.WindHeightInputModeEnum windHeightInputMode, double windDirection, WindAndSpreadOrientationMode.WindAndSpreadOrientationModeEnum windAndSpreadOrientationMode, double slope, SlopeUnits.SlopeUnitsEnum slopeUnits, double aspect, double canopyCover, FractionUnits.FractionUnitsEnum fractionUnits, double canopyHeight, double canopyBaseHeight, LengthUnits.LengthUnitsEnum canopyHeightUnits, double crownRatio, FractionUnits.FractionUnitsEnum crownRatioUnits, double canopyBulkDensity, DensityUnits.DensityUnitsEnum densityUnits) {
    BehaveCorePINVOKE.Crown_updateCrownInputs(swigCPtr, fuelModelNumber, moistureOneHour, moistureTenHour, moistureHundredHour, moistureLiveHerbaceous, moistureLiveWoody, moistureFoliar, (int)moistureUnits, windSpeed, (int)windSpeedUnits, (int)windHeightInputMode, windDirection, (int)windAndSpreadOrientationMode, slope, (int)slopeUnits, aspect, canopyCover, (int)fractionUnits, canopyHeight, canopyBaseHeight, (int)canopyHeightUnits, crownRatio, (int)crownRatioUnits, canopyBulkDensity, (int)densityUnits);
  }

  public void setCanopyBaseHeight(double canopyBaseHeight, LengthUnits.LengthUnitsEnum canopyHeightUnits) {
    BehaveCorePINVOKE.Crown_setCanopyBaseHeight(swigCPtr, canopyBaseHeight, (int)canopyHeightUnits);
  }

  public void setCanopyBulkDensity(double canopyBulkDensity, DensityUnits.DensityUnitsEnum densityUnits) {
    BehaveCorePINVOKE.Crown_setCanopyBulkDensity(swigCPtr, canopyBulkDensity, (int)densityUnits);
  }

  public void setMoistureFoliar(double foliarMoisture, FractionUnits.FractionUnitsEnum moistureUnits) {
    BehaveCorePINVOKE.Crown_setMoistureFoliar(swigCPtr, foliarMoisture, (int)moistureUnits);
  }

  public double getCanopyBaseHeight(LengthUnits.LengthUnitsEnum canopyHeightUnits) {
    double ret = BehaveCorePINVOKE.Crown_getCanopyBaseHeight(swigCPtr, (int)canopyHeightUnits);
    return ret;
  }

  public double getCanopyBulkDensity(DensityUnits.DensityUnitsEnum canopyBulkDensityUnits) {
    double ret = BehaveCorePINVOKE.Crown_getCanopyBulkDensity(swigCPtr, (int)canopyBulkDensityUnits);
    return ret;
  }

  public double getMoistureFoliar(FractionUnits.FractionUnitsEnum moistureUnits) {
    double ret = BehaveCorePINVOKE.Crown_getMoistureFoliar(swigCPtr, (int)moistureUnits);
    return ret;
  }

  public double getCrownFireSpreadRate(SpeedUnits.SpeedUnitsEnum spreadRateUnits) {
    double ret = BehaveCorePINVOKE.Crown_getCrownFireSpreadRate(swigCPtr, (int)spreadRateUnits);
    return ret;
  }

  public double getCrownFireSpreadDistance(LengthUnits.LengthUnitsEnum lengthUnits, double elapsedTime, TimeUnits.TimeUnitsEnum timeUnits) {
    double ret = BehaveCorePINVOKE.Crown_getCrownFireSpreadDistance(swigCPtr, (int)lengthUnits, elapsedTime, (int)timeUnits);
    return ret;
  }

  public double getSurfaceFireSpreadRate(SpeedUnits.SpeedUnitsEnum spreadRateUnits) {
    double ret = BehaveCorePINVOKE.Crown_getSurfaceFireSpreadRate(swigCPtr, (int)spreadRateUnits);
    return ret;
  }

  public double getSurfaceFireSpreadDistance(LengthUnits.LengthUnitsEnum lengthUnits, double elapsedTime, TimeUnits.TimeUnitsEnum timeUnits) {
    double ret = BehaveCorePINVOKE.Crown_getSurfaceFireSpreadDistance(swigCPtr, (int)lengthUnits, elapsedTime, (int)timeUnits);
    return ret;
  }

  public double getCrownFirelineIntensity(FirelineIntensityUnits.FirelineIntensityUnitsEnum firelineIntensityUnits) {
    double ret = BehaveCorePINVOKE.Crown_getCrownFirelineIntensity(swigCPtr, (int)firelineIntensityUnits);
    return ret;
  }

  public double getCrownFlameLength(LengthUnits.LengthUnitsEnum flameLengthUnits) {
    double ret = BehaveCorePINVOKE.Crown_getCrownFlameLength(swigCPtr, (int)flameLengthUnits);
    return ret;
  }

  public FireType.FireTypeEnum getFireType() {
    FireType.FireTypeEnum ret = (FireType.FireTypeEnum)BehaveCorePINVOKE.Crown_getFireType(swigCPtr);
    return ret;
  }

  public double getFinalSpreadRate(SpeedUnits.SpeedUnitsEnum spreadRateUnits) {
    double ret = BehaveCorePINVOKE.Crown_getFinalSpreadRate(swigCPtr, (int)spreadRateUnits);
    return ret;
  }

  public double getFinalHeatPerUnitArea(HeatPerUnitAreaUnits.HeatPerUnitAreaUnitsEnum heatPerUnitAreaUnits) {
    double ret = BehaveCorePINVOKE.Crown_getFinalHeatPerUnitArea(swigCPtr, (int)heatPerUnitAreaUnits);
    return ret;
  }

  public double getFinalFirelineIntesity(FirelineIntensityUnits.FirelineIntensityUnitsEnum firelineIntensityUnits) {
    double ret = BehaveCorePINVOKE.Crown_getFinalFirelineIntesity(swigCPtr, (int)firelineIntensityUnits);
    return ret;
  }

  public double getFinalFlameLength(LengthUnits.LengthUnitsEnum flameLengthUnits) {
    double ret = BehaveCorePINVOKE.Crown_getFinalFlameLength(swigCPtr, (int)flameLengthUnits);
    return ret;
  }

  public double getCrownFireLengthToWidthRatio() {
    double ret = BehaveCorePINVOKE.Crown_getCrownFireLengthToWidthRatio(swigCPtr);
    return ret;
  }

  public double getCrownFireArea(AreaUnits.AreaUnitsEnum areaUnits, double elapsedTime, TimeUnits.TimeUnitsEnum timeUnits) {
    double ret = BehaveCorePINVOKE.Crown_getCrownFireArea(swigCPtr, (int)areaUnits, elapsedTime, (int)timeUnits);
    return ret;
  }

  public double getCrownFirePerimeter(LengthUnits.LengthUnitsEnum lengthUnits, double elapsedTime, TimeUnits.TimeUnitsEnum timeUnits) {
    double ret = BehaveCorePINVOKE.Crown_getCrownFirePerimeter(swigCPtr, (int)lengthUnits, elapsedTime, (int)timeUnits);
    return ret;
  }

  public double getCriticalOpenWindSpeed(SpeedUnits.SpeedUnitsEnum speedUnits) {
    double ret = BehaveCorePINVOKE.Crown_getCriticalOpenWindSpeed(swigCPtr, (int)speedUnits);
    return ret;
  }

  public double getCrownFractionBurned() {
    double ret = BehaveCorePINVOKE.Crown_getCrownFractionBurned(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_std__string getFuelCode(int fuelModelNumber) {
    SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(BehaveCorePINVOKE.Crown_getFuelCode(swigCPtr, fuelModelNumber), true);
    return ret;
  }

  public SWIGTYPE_p_std__string getFuelName(int fuelModelNumber) {
    SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(BehaveCorePINVOKE.Crown_getFuelName(swigCPtr, fuelModelNumber), true);
    return ret;
  }

  public double getFuelbedDepth(int fuelModelNumber, LengthUnits.LengthUnitsEnum lengthUnits) {
    double ret = BehaveCorePINVOKE.Crown_getFuelbedDepth(swigCPtr, fuelModelNumber, (int)lengthUnits);
    return ret;
  }

  public double getFuelMoistureOfExtinctionDead(int fuelModelNumber, FractionUnits.FractionUnitsEnum moistureUnits) {
    double ret = BehaveCorePINVOKE.Crown_getFuelMoistureOfExtinctionDead(swigCPtr, fuelModelNumber, (int)moistureUnits);
    return ret;
  }

  public double getFuelHeatOfCombustionDead(int fuelModelNumber, HeatOfCombustionUnits.HeatOfCombustionUnitsEnum heatOfCombustionUnits) {
    double ret = BehaveCorePINVOKE.Crown_getFuelHeatOfCombustionDead(swigCPtr, fuelModelNumber, (int)heatOfCombustionUnits);
    return ret;
  }

  public double getFuelHeatOfCombustionLive(int fuelModelNumber, HeatOfCombustionUnits.HeatOfCombustionUnitsEnum heatOfCombustionUnits) {
    double ret = BehaveCorePINVOKE.Crown_getFuelHeatOfCombustionLive(swigCPtr, fuelModelNumber, (int)heatOfCombustionUnits);
    return ret;
  }

  public double getFuelLoadOneHour(int fuelModelNumber, LoadingUnits.LoadingUnitsEnum loadingUnits) {
    double ret = BehaveCorePINVOKE.Crown_getFuelLoadOneHour(swigCPtr, fuelModelNumber, (int)loadingUnits);
    return ret;
  }

  public double getFuelLoadTenHour(int fuelModelNumber, LoadingUnits.LoadingUnitsEnum loadingUnits) {
    double ret = BehaveCorePINVOKE.Crown_getFuelLoadTenHour(swigCPtr, fuelModelNumber, (int)loadingUnits);
    return ret;
  }

  public double getFuelLoadHundredHour(int fuelModelNumber, LoadingUnits.LoadingUnitsEnum loadingUnits) {
    double ret = BehaveCorePINVOKE.Crown_getFuelLoadHundredHour(swigCPtr, fuelModelNumber, (int)loadingUnits);
    return ret;
  }

  public double getFuelLoadLiveHerbaceous(int fuelModelNumber, LoadingUnits.LoadingUnitsEnum loadingUnits) {
    double ret = BehaveCorePINVOKE.Crown_getFuelLoadLiveHerbaceous(swigCPtr, fuelModelNumber, (int)loadingUnits);
    return ret;
  }

  public double getFuelLoadLiveWoody(int fuelModelNumber, LoadingUnits.LoadingUnitsEnum loadingUnits) {
    double ret = BehaveCorePINVOKE.Crown_getFuelLoadLiveWoody(swigCPtr, fuelModelNumber, (int)loadingUnits);
    return ret;
  }

  public double getFuelSavrOneHour(int fuelModelNumber, SurfaceAreaToVolumeUnits.SurfaceAreaToVolumeUnitsEnum savrUnits) {
    double ret = BehaveCorePINVOKE.Crown_getFuelSavrOneHour(swigCPtr, fuelModelNumber, (int)savrUnits);
    return ret;
  }

  public double getFuelSavrLiveHerbaceous(int fuelModelNumber, SurfaceAreaToVolumeUnits.SurfaceAreaToVolumeUnitsEnum savrUnits) {
    double ret = BehaveCorePINVOKE.Crown_getFuelSavrLiveHerbaceous(swigCPtr, fuelModelNumber, (int)savrUnits);
    return ret;
  }

  public double getFuelSavrLiveWoody(int fuelModelNumber, SurfaceAreaToVolumeUnits.SurfaceAreaToVolumeUnitsEnum savrUnits) {
    double ret = BehaveCorePINVOKE.Crown_getFuelSavrLiveWoody(swigCPtr, fuelModelNumber, (int)savrUnits);
    return ret;
  }

  public bool isFuelDynamic(int fuelModelNumber) {
    bool ret = BehaveCorePINVOKE.Crown_isFuelDynamic(swigCPtr, fuelModelNumber);
    return ret;
  }

  public bool isFuelModelDefined(int fuelModelNumber) {
    bool ret = BehaveCorePINVOKE.Crown_isFuelModelDefined(swigCPtr, fuelModelNumber);
    return ret;
  }

  public bool isFuelModelReserved(int fuelModelNumber) {
    bool ret = BehaveCorePINVOKE.Crown_isFuelModelReserved(swigCPtr, fuelModelNumber);
    return ret;
  }

  public bool isAllFuelLoadZero(int fuelModelNumber) {
    bool ret = BehaveCorePINVOKE.Crown_isAllFuelLoadZero(swigCPtr, fuelModelNumber);
    return ret;
  }

  public void updateCrownsSurfaceInputs(int fuelModelNumber, double moistureOneHour, double moistureTenHour, double moistureHundredHour, double moistureLiveHerbaceous, double moistureLiveWoody, FractionUnits.FractionUnitsEnum moistureUnits, double windSpeed, SpeedUnits.SpeedUnitsEnum windSpeedUnits, WindHeightInputMode.WindHeightInputModeEnum windHeightInputMode, double windDirection, WindAndSpreadOrientationMode.WindAndSpreadOrientationModeEnum windAndSpreadOrientationMode, double slope, SlopeUnits.SlopeUnitsEnum slopeUnits, double aspect, double canopyCover, FractionUnits.FractionUnitsEnum fractionUnits, double canopyHeight, LengthUnits.LengthUnitsEnum canopyHeightUnits, double crownRatio, FractionUnits.FractionUnitsEnum crownRatioUnits) {
    BehaveCorePINVOKE.Crown_updateCrownsSurfaceInputs(swigCPtr, fuelModelNumber, moistureOneHour, moistureTenHour, moistureHundredHour, moistureLiveHerbaceous, moistureLiveWoody, (int)moistureUnits, windSpeed, (int)windSpeedUnits, (int)windHeightInputMode, windDirection, (int)windAndSpreadOrientationMode, slope, (int)slopeUnits, aspect, canopyCover, (int)fractionUnits, canopyHeight, (int)canopyHeightUnits, crownRatio, (int)crownRatioUnits);
  }

  public void setCanopyCover(double canopyCover, FractionUnits.FractionUnitsEnum fractionUnits) {
    BehaveCorePINVOKE.Crown_setCanopyCover(swigCPtr, canopyCover, (int)fractionUnits);
  }

  public void setCanopyHeight(double canopyHeight, LengthUnits.LengthUnitsEnum canopyHeightUnits) {
    BehaveCorePINVOKE.Crown_setCanopyHeight(swigCPtr, canopyHeight, (int)canopyHeightUnits);
  }

  public void setCrownRatio(double crownRatio, FractionUnits.FractionUnitsEnum crownRatioUnits) {
    BehaveCorePINVOKE.Crown_setCrownRatio(swigCPtr, crownRatio, (int)crownRatioUnits);
  }

  public void setFuelModelNumber(int fuelModelNumber) {
    BehaveCorePINVOKE.Crown_setFuelModelNumber(swigCPtr, fuelModelNumber);
  }

  public void setMoistureOneHour(double moistureOneHour, FractionUnits.FractionUnitsEnum moistureUnits) {
    BehaveCorePINVOKE.Crown_setMoistureOneHour(swigCPtr, moistureOneHour, (int)moistureUnits);
  }

  public void setMoistureTenHour(double moistureTenHour, FractionUnits.FractionUnitsEnum moistureUnits) {
    BehaveCorePINVOKE.Crown_setMoistureTenHour(swigCPtr, moistureTenHour, (int)moistureUnits);
  }

  public void setMoistureHundredHour(double moistureHundredHour, FractionUnits.FractionUnitsEnum moistureUnits) {
    BehaveCorePINVOKE.Crown_setMoistureHundredHour(swigCPtr, moistureHundredHour, (int)moistureUnits);
  }

  public void setMoistureDeadAggregate(double moistureDead, FractionUnits.FractionUnitsEnum moistureUnits) {
    BehaveCorePINVOKE.Crown_setMoistureDeadAggregate(swigCPtr, moistureDead, (int)moistureUnits);
  }

  public void setMoistureLiveHerbaceous(double moistureLiveHerbaceous, FractionUnits.FractionUnitsEnum moistureUnits) {
    BehaveCorePINVOKE.Crown_setMoistureLiveHerbaceous(swigCPtr, moistureLiveHerbaceous, (int)moistureUnits);
  }

  public void setMoistureLiveWoody(double moistureLiveWoody, FractionUnits.FractionUnitsEnum moistureUnits) {
    BehaveCorePINVOKE.Crown_setMoistureLiveWoody(swigCPtr, moistureLiveWoody, (int)moistureUnits);
  }

  public void setMoistureLiveAggregate(double moistureLive, FractionUnits.FractionUnitsEnum moistureUnits) {
    BehaveCorePINVOKE.Crown_setMoistureLiveAggregate(swigCPtr, moistureLive, (int)moistureUnits);
  }

  public void setMoistureScenarios(SWIGTYPE_p_MoistureScenarios moistureScenarios) {
    BehaveCorePINVOKE.Crown_setMoistureScenarios(swigCPtr, SWIGTYPE_p_MoistureScenarios.getCPtr(moistureScenarios));
    if (BehaveCorePINVOKE.SWIGPendingException.Pending) throw BehaveCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public bool setCurrentMoistureScenarioByName(SWIGTYPE_p_std__string moistureScenarioName) {
    bool ret = BehaveCorePINVOKE.Crown_setCurrentMoistureScenarioByName(swigCPtr, SWIGTYPE_p_std__string.getCPtr(moistureScenarioName));
    if (BehaveCorePINVOKE.SWIGPendingException.Pending) throw BehaveCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool setCurrentMoistureScenarioByIndex(int moistureScenarioIndex) {
    bool ret = BehaveCorePINVOKE.Crown_setCurrentMoistureScenarioByIndex(swigCPtr, moistureScenarioIndex);
    return ret;
  }

  public void setMoistureInputMode(MoistureInputMode.MoistureInputModeEnum moistureInputMode) {
    BehaveCorePINVOKE.Crown_setMoistureInputMode(swigCPtr, (int)moistureInputMode);
  }

  public void setSlope(double slope, SlopeUnits.SlopeUnitsEnum slopeUnits) {
    BehaveCorePINVOKE.Crown_setSlope(swigCPtr, slope, (int)slopeUnits);
  }

  public void setAspect(double aspect) {
    BehaveCorePINVOKE.Crown_setAspect(swigCPtr, aspect);
  }

  public void setWindSpeed(double windSpeed, SpeedUnits.SpeedUnitsEnum windSpeedUnits, WindHeightInputMode.WindHeightInputModeEnum windHeightInputMode) {
    BehaveCorePINVOKE.Crown_setWindSpeed(swigCPtr, windSpeed, (int)windSpeedUnits, (int)windHeightInputMode);
  }

  public void setWindDirection(double windDirection) {
    BehaveCorePINVOKE.Crown_setWindDirection(swigCPtr, windDirection);
  }

  public void setWindHeightInputMode(WindHeightInputMode.WindHeightInputModeEnum windHeightInputMode) {
    BehaveCorePINVOKE.Crown_setWindHeightInputMode(swigCPtr, (int)windHeightInputMode);
  }

  public void setWindAndSpreadOrientationMode(WindAndSpreadOrientationMode.WindAndSpreadOrientationModeEnum windAndSpreadAngleMode) {
    BehaveCorePINVOKE.Crown_setWindAndSpreadOrientationMode(swigCPtr, (int)windAndSpreadAngleMode);
  }

  public void setUserProvidedWindAdjustmentFactor(double userProvidedWindAdjustmentFactor) {
    BehaveCorePINVOKE.Crown_setUserProvidedWindAdjustmentFactor(swigCPtr, userProvidedWindAdjustmentFactor);
  }

  public void setWindAdjustmentFactorCalculationMethod(WindAdjustmentFactorCalculationMethod.WindAdjustmentFactorCalculationMethodEnum windAdjustmentFactorCalculationMethod) {
    BehaveCorePINVOKE.Crown_setWindAdjustmentFactorCalculationMethod(swigCPtr, (int)windAdjustmentFactorCalculationMethod);
  }

  public int getFuelModelNumber() {
    int ret = BehaveCorePINVOKE.Crown_getFuelModelNumber(swigCPtr);
    return ret;
  }

  public double getMoistureOneHour(FractionUnits.FractionUnitsEnum moistureUnits) {
    double ret = BehaveCorePINVOKE.Crown_getMoistureOneHour(swigCPtr, (int)moistureUnits);
    return ret;
  }

  public double getMoistureTenHour(FractionUnits.FractionUnitsEnum moistureUnits) {
    double ret = BehaveCorePINVOKE.Crown_getMoistureTenHour(swigCPtr, (int)moistureUnits);
    return ret;
  }

  public double getMoistureHundredHour(FractionUnits.FractionUnitsEnum moistureUnits) {
    double ret = BehaveCorePINVOKE.Crown_getMoistureHundredHour(swigCPtr, (int)moistureUnits);
    return ret;
  }

  public double getMoistureLiveHerbaceous(FractionUnits.FractionUnitsEnum moistureUnits) {
    double ret = BehaveCorePINVOKE.Crown_getMoistureLiveHerbaceous(swigCPtr, (int)moistureUnits);
    return ret;
  }

  public double getMoistureLiveWoody(FractionUnits.FractionUnitsEnum moistureUnits) {
    double ret = BehaveCorePINVOKE.Crown_getMoistureLiveWoody(swigCPtr, (int)moistureUnits);
    return ret;
  }

  public int getNumberOfMoistureScenarios() {
    int ret = BehaveCorePINVOKE.Crown_getNumberOfMoistureScenarios(swigCPtr);
    return ret;
  }

  public int getMoistureScenarioIndexByName(SWIGTYPE_p_std__string name) {
    int ret = BehaveCorePINVOKE.Crown_getMoistureScenarioIndexByName(swigCPtr, SWIGTYPE_p_std__string.getCPtr(name));
    if (BehaveCorePINVOKE.SWIGPendingException.Pending) throw BehaveCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool getIsMoistureScenarioDefinedByName(SWIGTYPE_p_std__string name) {
    bool ret = BehaveCorePINVOKE.Crown_getIsMoistureScenarioDefinedByName(swigCPtr, SWIGTYPE_p_std__string.getCPtr(name));
    if (BehaveCorePINVOKE.SWIGPendingException.Pending) throw BehaveCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_std__string getMoistureScenarioDescriptionByName(SWIGTYPE_p_std__string name) {
    SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(BehaveCorePINVOKE.Crown_getMoistureScenarioDescriptionByName(swigCPtr, SWIGTYPE_p_std__string.getCPtr(name)), true);
    if (BehaveCorePINVOKE.SWIGPendingException.Pending) throw BehaveCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double getMoistureScenarioOneHourByName(SWIGTYPE_p_std__string name, FractionUnits.FractionUnitsEnum moistureUnits) {
    double ret = BehaveCorePINVOKE.Crown_getMoistureScenarioOneHourByName(swigCPtr, SWIGTYPE_p_std__string.getCPtr(name), (int)moistureUnits);
    if (BehaveCorePINVOKE.SWIGPendingException.Pending) throw BehaveCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double getMoistureScenarioTenHourByName(SWIGTYPE_p_std__string name, FractionUnits.FractionUnitsEnum moistureUnits) {
    double ret = BehaveCorePINVOKE.Crown_getMoistureScenarioTenHourByName(swigCPtr, SWIGTYPE_p_std__string.getCPtr(name), (int)moistureUnits);
    if (BehaveCorePINVOKE.SWIGPendingException.Pending) throw BehaveCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double getMoistureScenarioHundredHourByName(SWIGTYPE_p_std__string name, FractionUnits.FractionUnitsEnum moistureUnits) {
    double ret = BehaveCorePINVOKE.Crown_getMoistureScenarioHundredHourByName(swigCPtr, SWIGTYPE_p_std__string.getCPtr(name), (int)moistureUnits);
    if (BehaveCorePINVOKE.SWIGPendingException.Pending) throw BehaveCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double getMoistureScenarioLiveHerbaceousByName(SWIGTYPE_p_std__string name, FractionUnits.FractionUnitsEnum moistureUnits) {
    double ret = BehaveCorePINVOKE.Crown_getMoistureScenarioLiveHerbaceousByName(swigCPtr, SWIGTYPE_p_std__string.getCPtr(name), (int)moistureUnits);
    if (BehaveCorePINVOKE.SWIGPendingException.Pending) throw BehaveCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double getMoistureScenarioLiveWoodyByName(SWIGTYPE_p_std__string name, FractionUnits.FractionUnitsEnum moistureUnits) {
    double ret = BehaveCorePINVOKE.Crown_getMoistureScenarioLiveWoodyByName(swigCPtr, SWIGTYPE_p_std__string.getCPtr(name), (int)moistureUnits);
    if (BehaveCorePINVOKE.SWIGPendingException.Pending) throw BehaveCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool getIsMoistureScenarioDefinedByIndex(int index) {
    bool ret = BehaveCorePINVOKE.Crown_getIsMoistureScenarioDefinedByIndex(swigCPtr, index);
    return ret;
  }

  public SWIGTYPE_p_std__string getMoistureScenarioNameByIndex(int index) {
    SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(BehaveCorePINVOKE.Crown_getMoistureScenarioNameByIndex(swigCPtr, index), true);
    return ret;
  }

  public SWIGTYPE_p_std__string getMoistureScenarioDescriptionByIndex(int index) {
    SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(BehaveCorePINVOKE.Crown_getMoistureScenarioDescriptionByIndex(swigCPtr, index), true);
    return ret;
  }

  public double getMoistureScenarioOneHourByIndex(int index, FractionUnits.FractionUnitsEnum moistureUnits) {
    double ret = BehaveCorePINVOKE.Crown_getMoistureScenarioOneHourByIndex(swigCPtr, index, (int)moistureUnits);
    return ret;
  }

  public double getMoistureScenarioTenHourByIndex(int index, FractionUnits.FractionUnitsEnum moistureUnits) {
    double ret = BehaveCorePINVOKE.Crown_getMoistureScenarioTenHourByIndex(swigCPtr, index, (int)moistureUnits);
    return ret;
  }

  public double getMoistureScenarioHundredHourByIndex(int index, FractionUnits.FractionUnitsEnum moistureUnits) {
    double ret = BehaveCorePINVOKE.Crown_getMoistureScenarioHundredHourByIndex(swigCPtr, index, (int)moistureUnits);
    return ret;
  }

  public double getMoistureScenarioLiveHerbaceousByIndex(int index, FractionUnits.FractionUnitsEnum moistureUnits) {
    double ret = BehaveCorePINVOKE.Crown_getMoistureScenarioLiveHerbaceousByIndex(swigCPtr, index, (int)moistureUnits);
    return ret;
  }

  public double getMoistureScenarioLiveWoodyByIndex(int index, FractionUnits.FractionUnitsEnum moistureUnits) {
    double ret = BehaveCorePINVOKE.Crown_getMoistureScenarioLiveWoodyByIndex(swigCPtr, index, (int)moistureUnits);
    return ret;
  }

  public double getWindSpeed(SpeedUnits.SpeedUnitsEnum windSpeedUnits, WindHeightInputMode.WindHeightInputModeEnum windHeightInputMode) {
    double ret = BehaveCorePINVOKE.Crown_getWindSpeed(swigCPtr, (int)windSpeedUnits, (int)windHeightInputMode);
    return ret;
  }

  public double getWindDirection() {
    double ret = BehaveCorePINVOKE.Crown_getWindDirection(swigCPtr);
    return ret;
  }

  public double getSlope(SlopeUnits.SlopeUnitsEnum slopeUnits) {
    double ret = BehaveCorePINVOKE.Crown_getSlope(swigCPtr, (int)slopeUnits);
    return ret;
  }

  public double getAspect() {
    double ret = BehaveCorePINVOKE.Crown_getAspect(swigCPtr);
    return ret;
  }

  public double getCanopyCover(FractionUnits.FractionUnitsEnum canopyCoverUnits) {
    double ret = BehaveCorePINVOKE.Crown_getCanopyCover(swigCPtr, (int)canopyCoverUnits);
    return ret;
  }

  public double getCanopyHeight(LengthUnits.LengthUnitsEnum canopyHeighUnits) {
    double ret = BehaveCorePINVOKE.Crown_getCanopyHeight(swigCPtr, (int)canopyHeighUnits);
    return ret;
  }

  public double getCrownRatio(FractionUnits.FractionUnitsEnum crownRatioUnits) {
    double ret = BehaveCorePINVOKE.Crown_getCrownRatio(swigCPtr, (int)crownRatioUnits);
    return ret;
  }

}

}
