//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace BehavCore {

public class FirelineIntensityUnits : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal FirelineIntensityUnits(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FirelineIntensityUnits obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(FirelineIntensityUnits obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~FirelineIntensityUnits() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          BehavePINVOKE.delete_FirelineIntensityUnits(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public static double toBaseUnits(double value, FirelineIntensityUnits.FirelineIntensityUnitsEnum units) {
    double ret = BehavePINVOKE.FirelineIntensityUnits_toBaseUnits(value, (int)units);
    return ret;
  }

  public static double fromBaseUnits(double value, FirelineIntensityUnits.FirelineIntensityUnitsEnum units) {
    double ret = BehavePINVOKE.FirelineIntensityUnits_fromBaseUnits(value, (int)units);
    return ret;
  }

  public FirelineIntensityUnits() : this(BehavePINVOKE.new_FirelineIntensityUnits(), true) {
  }

  public enum FirelineIntensityUnitsEnum {
    BtusPerFootPerSecond,
    BtusPerFootPerMinute,
    KilojoulesPerMeterPerSecond,
    KilojoulesPerMeterPerMinute,
    KilowattsPerMeter
  }

}

}
