//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace BehavCore {

public class HeatSourceAndReactionIntensityUnits : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal HeatSourceAndReactionIntensityUnits(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(HeatSourceAndReactionIntensityUnits obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(HeatSourceAndReactionIntensityUnits obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~HeatSourceAndReactionIntensityUnits() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          BehavePINVOKE.delete_HeatSourceAndReactionIntensityUnits(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public static double toBaseUnits(double value, HeatSourceAndReactionIntensityUnits.HeatSourceAndReactionIntensityUnitsEnum units) {
    double ret = BehavePINVOKE.HeatSourceAndReactionIntensityUnits_toBaseUnits(value, (int)units);
    return ret;
  }

  public static double fromBaseUnits(double value, HeatSourceAndReactionIntensityUnits.HeatSourceAndReactionIntensityUnitsEnum units) {
    double ret = BehavePINVOKE.HeatSourceAndReactionIntensityUnits_fromBaseUnits(value, (int)units);
    return ret;
  }

  public HeatSourceAndReactionIntensityUnits() : this(BehavePINVOKE.new_HeatSourceAndReactionIntensityUnits(), true) {
  }

  public enum HeatSourceAndReactionIntensityUnitsEnum {
    BtusPerSquareFootPerMinute,
    BtusPerSquareFootPerSecond,
    KilojoulesPerSquareMeterPerSecond,
    KilojoulesPerSquareMeterPerMinute,
    KilowattsPerSquareMeter
  }

}

}
